- name: "Update apt cache and install {{ nginx_version }} on Ubuntu"
  apt:
    name: "{{ nginx_version }}"
    state: present
    update_cache: yes

- name: Copy virtualhost conf to server
  ansible.builtin.template:
    src: "templates/vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ virtualhost }}.conf"
  notify: Reload Nginx

- name: Enable new sites
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ virtualhost }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ virtualhost }}.conf"
    state: link
  notify: Reload Nginx