- hosts: all
  become: yes
  vars:
    server_name: "{{ inventory_hostname }}"
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx=1.18.0
        state: present
        update_cache: yes