- hosts: all
  become: yes
  tasks:
    - name: Wait 60 seconds till all VPS are ready
      wait_for_connection:
      timeout: 60

- hosts: webserver
  become: yes
  roles:
    - role: nginx
      tags: nginx
    - role: letsencrypt
      tags: cert

- hosts: loadbalancer
  become: yes
  roles:
    - role: loadbalance
      tags: lb