- hosts: all
  become: yes
  vars:
    server_name: "{{ inventory_hostname }}"
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: 1.18.0
        update_cache: yes