- hosts: all
  become: yes
  tasks:
    - name: Wait 100 seconds till all VPS are ready
      wait_for_connection:
      timeout: 100

- hosts: webserver
  become: yes
  roles:
    - role: nginx
      tags: nginx

- hosts: loadbalancer
  become: yes
  roles:
    - role: loadbalance
      tags: lb
    - role: letsencrypt
      tags: cert