- hosts: webserver
  become: yes
  
  vars:
    # List of virtualhosts
    virtualhosts:
      1:
        name: "{{ tf_hostname }}"
  
  vars_files:
    - ["roles/nginx/vars/{{ ansible_facts['distribution']|lower }}.yml"]

  roles:
    - role: nginx
      tags: nginx
    - role: letsencrypt
      tags: cert