openssl_version: "openssl=1.1.1f-1ubuntu2.12"
python3_version: "python3=3.8.2-0ubuntu2"
certbot_version: "certbot=0.40.0-1ubuntu0.1"

acme_challenge_type: http-01
acme_directory: https://acme-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: "certificate-reminders@{{ tf_hostname }}"
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/account/account.key
domain_name: "{{ tf_hostname }}"