#server_name: "{{ inventory_hostname }}"
nginx_version: "nginx=1.18.0-0ubuntu1.3"
document_root: /var/www
port_num: 80
virtualhost: "{{ inventory_hostname }}"
backends: "{{ tf_web }}"
lb: "{{ tf_lb }}"