- name: "Update apt cache and install {{ openssl_version }}, {{ python3_version }} and {{ certbot_version }}"
  apt:
    name: "{{ openssl_version }}, {{ python3_version }}, {{ certbot_version }}, acme-tiny"
    state: present
    update_cache: yes

- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
  - "account"
  - "certs"
  - "csrs"
  - "keys"    

- name: Generate an OpenSSL account key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_account_key }}"

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    privatekey_path: "{{ letsencrypt_keys_dir }}/{{ domain_name }}.key"
    common_name: "www.{{ domain_name }}"
    subject_alt_name: "DNS:{{ domain_name }}"

- name: "Create .well-known/acme-challenge directory"
  file:
    path: "/var/www/{{ domain_name }}/html/.well-known/acme-challenge"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify: Reload Nginx

- name: Flush handlers
  meta: flush_handlers

- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    path: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
    csr_path: "{{ letsencrypt_csrs_dir }}/{{ domain_name }}.csr"
    provider: acme
    acme_accountkey_path: "{{ letsencrypt_account_key }}"
    acme_challenge_path: "/var/www/{{ domain_name }}/html/.well-known/acme-challenge/"

- name: Copy ssl virtualhost conf to server
  ansible.builtin.template:
    src: "templates/vhost_ssl.conf.j2"
    dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
  notify: Reload Nginx

# - name: Add letsencrypt cronjob for cert renewal
#   cron:
#     name: letsencrypt_renewal
#     special_time: weekly
#     job: "certbot --renew-by-default certonly -n --webroot -w /etc/letsencrypt -m {{ acme_email }} --agree-tos -d {{ domain_name }} -d www.{{ domain_name }} && service nginx reload"
 
  # certbot --renew-by-default certonly -n --webroot -w /etc/letsencrypt -m certificate-reminders@olegen.devops.rebrain.srwx.net --agree-tos -d olegen.devops.rebrain.srwx.net -d www.olegen.devops.rebrain.srwx.net  && service nginx reload