- name: "Update apt cache and install {{ openssl_version }}, {{ python3_version }} and {{ certbot_version }}"
  apt:
    name: "{{ openssl_version }}, {{ python3_version }}, {{ certbot_version }}"
    state: present
    update_cache: yes

- name: "Create letsencrypt directory"
  file:
    path: "/var/www/{{ domain_name }}/html/letsencrypt"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x

# reload nginx after installation
- name: Flush handlers
  meta: flush_handlers

- name: Create letsencrypt certificate
  shell: "certbot certonly -n --webroot -w /var/www/{{ domain_name }}/html/letsencrypt -m {{ acme_email }} --agree-tos -d {{ domain_name }} -d www.{{ domain_name }}"
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}"

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem    

- name: Copy ssl virtualhost conf to server
  ansible.builtin.template:
    src: "templates/vhost_ssl.conf.j2"
    dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
  notify: Reload Nginx

- name: Flush handlers
  meta: flush_handlers

# add cert renewal at cron
- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: "certbot --renew-by-default certonly -n --webroot -w /etc/letsencrypt -m {{ acme_email }} --agree-tos -d {{ domain_name }} -d www.{{ domain_name }} && service nginx reload"